-- Plan #11 — Slack thread-per-theme registry.
--
-- The nightly crons (scheduled_dream / scheduled_forecast /
-- scheduled_investigation / cost-digest / pipeline-review) used to fan out
-- as separate top-level channel messages. The new shape is: one parent
-- message per THEME per nightly run, with every artifact, chart, table,
-- and sub-finding for that theme posted as a REPLY in the same thread.
--
-- This table caches the (run_id, theme, channel_id) → thread_ts mapping
-- so that:
--
--   1. Multiple post_report calls within one cron's runtime route to the
--      same thread without re-posting the parent.
--   2. A container restart mid-run does NOT fork into a second thread.
--      The in-memory cache in slack_thread_registry rebuilds from this
--      table on first lookup after restart.
--
-- Themes (one per cron job per run):
--   - pipeline_review
--   - forecast_analysis
--   - dream_plan
--   - investigation_finding   (multiple per run = multiple threads)
--   - cost_report
--
-- run_id is generated by the cron entry point (typically a date-keyed
-- string like "nightly-2026-05-14") and threaded through every
-- post_report call that belongs to that run. Two crons running on the
-- same calendar day with different themes get different rows; the same
-- cron running on two days gets two rows under two run_ids.
--
-- The table is idempotent — re-running this migration is a no-op
-- thanks to IF NOT EXISTS clauses on both table and index.

CREATE TABLE IF NOT EXISTS nightly_run_threads (
    run_id      TEXT        NOT NULL,
    theme       TEXT        NOT NULL,
    channel_id  TEXT        NOT NULL,
    thread_ts   TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (run_id, theme, channel_id)
);

-- Lookup by run_id alone (e.g. "which themes did tonight's run touch?")
-- is rare enough that the PK prefix is enough; no secondary index.
